-- MySQL Script generated by MySQL Workbench
-- qui 08 mai 2025 14:18:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema renascer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema renascer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `renascer` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_pagamento` (
  `idpagamento` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `forma` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB;

USE `renascer` ;

-- -----------------------------------------------------
-- Table `renascer`.`tb_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renascer`.`tb_servico` (
  `idservico` INT(11) NOT NULL AUTO_INCREMENT,
  `preco_servico` DECIMAL(10,2) NOT NULL,
  `tipo_servico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idservico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `renascer`.`tb_taxa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renascer`.`tb_taxa` (
  `idtaxa` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `taxa` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idtaxa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `renascer`.`tb_agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renascer`.`tb_agendamento` (
  `idagendamento` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `tb_taxa_idtaxa` INT(11) NOT NULL,
  `tb_servico_id_servico` INT(11) NOT NULL,
  PRIMARY KEY (`idagendamento`),
  INDEX `fk_tb_agendamento_tb_taxa1_idx` (`tb_taxa_idtaxa` ASC) VISIBLE,
  INDEX `fk_tb_agendamento_tb_servico1_idx` (`tb_servico_id_servico` ASC) VISIBLE,
  CONSTRAINT `fk_tb_agendamento_tb_servico1`
    FOREIGN KEY (`tb_servico_id_servico`)
    REFERENCES `renascer`.`tb_servico` (`idservico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_agendamento_tb_taxa1`
    FOREIGN KEY (`tb_taxa_idtaxa`)
    REFERENCES `renascer`.`tb_taxa` (`idtaxa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `renascer`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renascer`.`tb_usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `tb_pagamento_idpagamento` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_tb_usuario_tb_pagamento1_idx` (`tb_pagamento_idpagamento` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_tb_pagamento1`
    FOREIGN KEY (`tb_pagamento_idpagamento`)
    REFERENCES `mydb`.`tb_pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `renascer`.`tb_agendamento_has_tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renascer`.`tb_agendamento_has_tb_usuario` (
  `tb_agendamento_idagendamento` INT(11) NOT NULL,
  `tb_usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`tb_agendamento_idagendamento`, `tb_usuario_idusuario`),
  INDEX `fk_tb_agendamento_has_tb_usuario_tb_usuario1_idx` (`tb_usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_tb_agendamento_has_tb_usuario_tb_agendamento1_idx` (`tb_agendamento_idagendamento` ASC) VISIBLE,
  CONSTRAINT `fk_tb_agendamento_has_tb_usuario_tb_agendamento1`
    FOREIGN KEY (`tb_agendamento_idagendamento`)
    REFERENCES `renascer`.`tb_agendamento` (`idagendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_agendamento_has_tb_usuario_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idusuario`)
    REFERENCES `renascer`.`tb_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

