-- MySQL Script generated by MySQL Workbench
-- qui 25 set 2025 10:32:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema renascer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema renascer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `renascer` ;
USE `renascer` ;

-- -----------------------------------------------------
-- Table `renascer`.`tb_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renascer`.`tb_servico` (
  `idservico` INT NOT NULL AUTO_INCREMENT,
  `preco_servico` DECIMAL(10,2) NOT NULL,
  `tipo_servico` VARCHAR(10) NOT NULL,
  `descricao_servico` VARCHAR(800) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idservico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `renascer`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renascer`.`tb_usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `renascer`.`tb_agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renascer`.`tb_agendamento` (
  `idagendamento` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `tb_servico_id_servico` INT NOT NULL,
  `tb_usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idagendamento`),
  INDEX `fk_tb_agendamento_tb_servico1_idx` (`tb_servico_id_servico` ASC) VISIBLE,
  INDEX `fk_tb_agendamento_tb_usuario2_idx` (`tb_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_agendamento_tb_servico1`
    FOREIGN KEY (`tb_servico_id_servico`)
    REFERENCES `renascer`.`tb_servico` (`idservico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_agendamento_tb_usuario2`
    FOREIGN KEY (`tb_usuario_idusuario`)
    REFERENCES `renascer`.`tb_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `renascer`.`tb_taxa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renascer`.`tb_taxa` (
  `idtaxa` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `taxa` DECIMAL(10,2) NULL DEFAULT NULL,
  `tb_agendamento_idagendamento` INT NOT NULL,
  PRIMARY KEY (`idtaxa`),
  INDEX `fk_tb_taxa_tb_agendamento1_idx` (`tb_agendamento_idagendamento` ASC) VISIBLE,
  CONSTRAINT `fk_tb_taxa_tb_agendamento1`
    FOREIGN KEY (`tb_agendamento_idagendamento`)
    REFERENCES `renascer`.`tb_agendamento` (`idagendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `renascer`.`tb_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renascer`.`tb_pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `forma` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `tb_agendamento_idagendamento` INT NOT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_tb_pagamento_tb_agendamento1_idx` (`tb_agendamento_idagendamento` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pagamento_tb_agendamento1`
    FOREIGN KEY (`tb_agendamento_idagendamento`)
    REFERENCES `renascer`.`tb_agendamento` (`idagendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE renascer;

-- Inserir usuários (cliente = 'c', funcionário = 'f', gerente = 'g')
INSERT INTO tb_usuario (email, senha, tipo, nome, telefone) VALUES
('marilene.gerente@gmail.com', 'senha123', 'g', 'Marilene', '11 988887770'),
('maria.cliente@gmail.com', 'senha123', 'c', 'Maria Souza', '11 988887777'),
('joao.cliente@gmail.com', 'senha123', 'c', 'João Silva', '11 977776666'),
('ana.cliente@gmail.com', 'senha123', 'c', 'Ana Pereira', '11 966665555'),
('carla.cliente@gmail.com', 'c123', 'c', 'Carla Dias', '11 955554444'),
('paulo.cliente@gmail.com', 'senha123', 'c', 'Paulo Oliveira', '11 944443333'),
('jose.func@gmail.com', 'senha123', 'f', 'José Barbosa', '11 933332222'),
('lucas.func@gmail.com', 'senha123', 'f', 'Lucas Martins', '11 922221111'),
('fernanda.func@gmail.com', 'senha123', 'f', 'Fernanda Lima', '11 911110000'),
('aline.func@gmail.com', 'senha123', 'f', 'Aline Ferreira', '11 900009999');

-- Inserir serviços
INSERT INTO tb_servico (preco_servico, tipo_servico, descricao_servico, foto) VALUES
(50.00, 'Cabelo', 'Corte de cabelo feminino', 'corte_feminino.jpg'),
(40.00, 'Cabelo', 'Corte de cabelo masculino', 'corte_masculino.jpg'),
(120.00, 'Cabelo', 'Coloração completa', 'coloracao.jpg'),
(80.00, 'Cabelo', 'Escova progressiva', 'escova.jpg'),
(150.00, 'Cabelo', 'Luzes no cabelo', 'luzes.jpg'),
(60.00, 'Cabelo', 'Cabelo completo com hidratação', 'cabelo.jpg'),
(200.00, 'Penteado', 'Penteado para festa', 'penteado.jpg'),
(100.00, 'Maquiagem', 'Maquiagem completa', 'maquiagem.jpg'),
(80.00, 'Unha', 'Manicure completa', 'manicure.jpg'),
(300.00, 'Especial', 'Pacote noiva completo', 'noiva.jpg');

-- Inserir agendamentos (associando cliente + serviço)
INSERT INTO tb_agendamento (data, horario, tb_servico_id_servico, tb_usuario_idusuario) VALUES
('2025-09-15', '10:00:00', 1, 2),
('2025-09-15', '11:00:00', 2, 3),
('2025-09-16', '14:00:00', 3, 4),
('2025-09-16', '15:00:00', 4, 5),
('2025-09-17', '09:00:00', 5, 6),
('2025-09-17', '10:00:00', 6, 2),
('2025-09-18', '13:00:00', 7, 3),
('2025-09-18', '14:00:00', 8, 4),
('2025-09-19', '15:00:00', 9, 5),
('2025-09-20', '16:00:00', 10, 6);

-- Inserir taxas
INSERT INTO tb_taxa (status, taxa, tb_agendamento_idagendamento) VALUES
('pendente', 10.00, 1),
('pago', 5.00, 2),
('pendente', 12.00, 3),
('pago', 8.00, 4),
('pendente', 15.00, 5),
('pago', 6.00, 6),
('pendente', 10.00, 7),
('pago', 5.00, 8),
('pendente', 7.00, 9),
('pago', 20.00, 10);

-- Inserir pagamentos
INSERT INTO tb_pagamento (valor, forma, descricao, tb_agendamento_idagendamento) VALUES
(50.00, 'Cartão', 'Pagamento corte feminino', 1),
(40.00, 'Dinheiro', 'Pagamento corte masculino', 2),
(120.00, 'Cartão', 'Pagamento coloração', 3),
(80.00, 'Pix', 'Pagamento escova progressiva', 4),
(150.00, 'Cartão', 'Pagamento luzes', 5),
(60.00, 'Dinheiro', 'Pagamento hidratação', 6),
(200.00, 'Cartão', 'Pagamento penteado festa', 7),
(100.00, 'Pix', 'Pagamento maquiagem', 8),
(80.00, 'Dinheiro', 'Pagamento manicure', 9),
(300.00, 'Cartão', 'Pagamento pacote noiva', 10);
